# Generated by Django 3.0 on 2021-03-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redacción',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('fechacreada', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'Internacionales'), (2, 'Nacionales'), (3, 'Policiales'), (4, 'Deportes')])),
                ('imagen', models.ImageField(upload_to='categorias')),
            ],
        ),
    ]
