# Generated by Django 3.0 on 2021-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
