# Generated by Django 3.0 on 2021-03-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacción',
            old_name='fechacreada',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='redacción',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
