# Generated by Django 3.0 on 2021-03-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacción',
            name='fecha',
            field=models.DateField(),
        ),
    ]
