# Generated by Django 3.0 on 2021-03-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20210318_1840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Redacción',
            new_name='Redaccion',
        ),
    ]
