# Generated by Django 3.0 on 2021-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20210315_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacción',
            name='fecha',
            field=models.TimeField(),
        ),
    ]
