# Generated by Django 3.0 on 2021-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20210319_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaccion',
            name='categoria',
            field=models.IntegerField(blank=True, choices=[(1, 'Internacionales'), (2, 'Nacionales'), (3, 'Policiales'), (4, 'Deportes')], null=True),
        ),
    ]
