# Generated by Django 3.0 on 2021-03-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20210315_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redacción',
            old_name='status',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='redacción',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
