# Generated by Django 3.0 on 2021-03-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_redaccion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaccion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
