# Generated by Django 3.0 on 2021-03-16 21:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_auto_20210316_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacción',
            name='hora',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 16, 21, 26, 26, 476375, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
