# Generated by Django 3.0 on 2021-03-16 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0007_remove_redacción_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='redacción',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 3, 16, 22, 2, 59, 138429, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
